version: '2'
services:
    whereqrealtor-app:
        image: whereqrealtor
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://whereqrealtor-postgresql:5432/WhereQRealtor
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    whereqrealtor-postgresql:
        extends:
            file: postgresql.yml
            service: whereqrealtor-postgresql
